apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
    # Below Port number is a service port number
    - port: 8081
      # Below targetPort is a Container Port number
      targetPort: 8081