apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    # Below Port number is a service port number
    - port: 27017
      # Below targetPort is a Container Port number
      targetPort: 27017