apiVersion: v1
kind: Pod
metadata:
  name: request-limits-resource-demo
spec:
  containers:
    - name: request-resource
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "2", "--vm", "1", "--vm-bytes", "1G", "--vm-hang", "1"]
      resources:
      #### requests check k8's nodes avaialibility of mentions cpu and memory resources
      #### if the requested CPU and Memory avaialible then only pod is created 
        requests:
          cpu: "1"
          memory: "1Gi"
      ### In Limits we mention max CPU and Memory usage for POD
        limits:
          cpu: "1"
          memory: "1Gi"
