apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.3
          ports:
            - containerPort: 80