apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    # Below Port number is a service port number
    - port: 8081
      # Below targetPort is a Container Port number
      targetPort: 80
      #nodePort: 30000