apiVersion: v1
kind: Pod
metadata:
  name: multy-container-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: ubuntu
    image: ubuntu/apache2:latest
    ports:
    - containerPort: 81
