apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group use "*" for named API group
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  verbs: ["get", "watch", "list"] # use "*" for all verbs 
  resources: ["pods", "pods/log"] # use "*" for all resources
