apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-readinessprobe-deployment
  annotations:
    kubernetes.io/change-cause: "Updating to alipine version"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10  ## Liveness probe executed after 10 or N seconds dealy after apllication set up
            periodSeconds: 10 ## Liveness probe is executed for every 10 or N seconds
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2 ## Number of Liveness probe failures, container restarts after failureThreshold is 2 or N 
          ports:
            - containerPort: 80